import localFont from "next/font/local";
import "./globals.css";

const kalpurush = localFont({
  src: "../public/fonts/kalpurush.ttf",
  variable: "--font-kalpurush",
  weight: "400",
  style: "normal",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kalpurush.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
